### ISSUE TITLE
Requirements.txt missing versions

### ISSUE THREAD

**Issue by WritingPanda** [Insane-Forensics/drovorub-hunt#1]
In order for users and other developers to use and develop on your tool, I would recommend specifying the versions of the dependencies in the requirements.txt file.

Better yet, I would recommend using Poetry (https://python-poetry.org/) for dependency management, but if you want to stick with pip, there's nothing wrong with that. Best way to accomplish this would be to do a pip freeze > requirements.txt to get the versions you are using for this project.

Poetry is a fantastic dependency management tool that does a lot for you, including collecting hashes of the dependencies, so users can confirm the integrity of the dependencies they are using.

**Comment by dgunter** [comment]
Thanks for the suggestion @WritingPanda . Issue has now been fixed and merged.
